# Model Selection and Validation

## Purpose
This notebook validates the Perspective API toxicity model by:
1. Setting up Perspective API model
2. Creating inference pipeline with 1-4 toxicity scale mapping
3. Validating model against expert-annotated ground truth
4. Calculating performance metrics

## Overview
- **Input**: validation_1043_comments.csv (from Notebook 1)
- **Output**: Validation predictions, performance report


In [20]:
import pandas as pd
import numpy as np
from pathlib import Path
import time
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

try:
    from googleapiclient import discovery
    import json
    PERSPECTIVE_AVAILABLE = True
except ImportError:
    PERSPECTIVE_AVAILABLE = False

try:
    from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

base_path = Path('../archive/SOCC')
validation_path = Path('../data/processed/validation_1043_comments.csv')
output_dir = Path('../data/processed')
output_dir.mkdir(parents=True, exist_ok=True)


In [21]:
df_validation = pd.read_csv(validation_path)
print(f"Loaded {len(df_validation)} comments")


Loaded 1043 comments


## Section 1: Model Setup

We'll set up the Perspective API model:
- **Perspective API** (Google) - Requires API key
- Get your API key from: https://developers.perspectiveapi.com/


In [22]:
PERSPECTIVE_API_KEY = "AIzaSyCTuW3z7pQhBQ8dwYicuo2sVIWie3e3OPQ"

perspective_client = None
if PERSPECTIVE_AVAILABLE and PERSPECTIVE_API_KEY:
    try:
        perspective_client = discovery.build(
            "commentanalyzer",
            "v1alpha1",
            developerKey=PERSPECTIVE_API_KEY,
            discoveryServiceUrl="https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1",
            static_discovery=False,
        )
    except Exception as e:
        print(f"Failed to initialize Perspective API: {e}")
        perspective_client = None


## Section 2: Toxicity Scale Mapping Functions

The Perspective API outputs continuous scores. We need to map these to the 4-level toxicity scale (1-4) used in the ground truth annotations.

**Scale Definition:**
- 1 = Least toxic / Not toxic
- 2 = Mildly toxic
- 3 = Moderately toxic  
- 4 = Highly toxic


In [23]:
def map_to_4_level_scale(score, method='equal_bins'):
    if pd.isna(score) or score is None:
        return np.nan
    
    score = max(0.0, min(1.0, float(score)))
    
    if method == 'equal_bins':
        if score < 0.25:
            return 1
        elif score < 0.5:
            return 2
        elif score < 0.75:
            return 3
        else:
            return 4
    elif method == 'threshold':
        if score < 0.3:
            return 1
        elif score < 0.6:
            return 2
        elif score < 0.85:
            return 3
        else:
            return 4
    else:
        raise ValueError(f"Unknown method: {method}")


In [24]:
def predict_perspective_api(text, client, max_retries=3, max_length=20000):
    if client is None or text is None or (isinstance(text, float) and pd.isna(text)) or str(text).strip() == "":
        return {"score": np.nan, "level": np.nan, "ok": False}

    text = str(text)
    if len(text) > max_length:
        text = text[:max_length]

    for attempt in range(max_retries):
        try:
            analyze_request = {
                "comment": {"text": text},
                "requestedAttributes": {
                    "TOXICITY": {},
                    "SEVERE_TOXICITY": {},
                    "INSULT": {},
                    "THREAT": {},
                    "IDENTITY_ATTACK": {},
                    "PROFANITY": {},
                },
                "doNotStore": True,
            }

            response = client.comments().analyze(body=analyze_request).execute()
            attr = response.get("attributeScores", {})

            def get_score(name):
                return attr.get(name, {}).get("summaryScore", {}).get("value", np.nan)

            scores = {
                "toxicity": get_score("TOXICITY"),
                "severe_toxicity": get_score("SEVERE_TOXICITY"),
                "insult": get_score("INSULT"),
                "threat": get_score("THREAT"),
                "identity_attack": get_score("IDENTITY_ATTACK"),
                "profanity": get_score("PROFANITY"),
            }

            # Main combined score (exclude profanity by default)
            combined_score = np.nanmax([
                scores["toxicity"],
                scores["severe_toxicity"],
                scores["insult"],
                scores["threat"],
                scores["identity_attack"],
            ])

            if pd.isna(combined_score):
                return {"score": np.nan, "level": np.nan, "ok": False}

            toxicity_level = map_to_4_level_scale(combined_score, method="equal_bins")

            return {
                "score": float(combined_score),
                "level": int(toxicity_level),
                "ok": True,
                **scores,  # keeps per-attribute scores too
            }

        except Exception as e:
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
            else:
                return {"score": np.nan, "level": np.nan, "ok": False}


In [25]:
df_val_clean = df_validation.copy()
df_val_clean['toxicity_level'] = pd.to_numeric(df_val_clean['toxicity_level'], errors='coerce')
df_val_clean = df_val_clean[df_val_clean['toxicity_level'].notna() & df_val_clean['comment_text'].notna()].copy()
print(f"Validation dataset: {len(df_val_clean)} comments")


Validation dataset: 1043 comments


In [26]:
if perspective_client is not None:
    perspective_predictions = []
    
    for idx, row in tqdm(df_val_clean.iterrows(), total=len(df_val_clean), desc="Perspective API"):
        result = predict_perspective_api(row["comment_text"], perspective_client)
        perspective_predictions.append(result)
        time.sleep(1.0)
    
    df_val_clean["perspective_score"] = [p["score"] for p in perspective_predictions]
    df_val_clean["perspective_level"] = [p["level"] for p in perspective_predictions]
    df_val_clean["perspective_ok"] = [p.get("ok", False) for p in perspective_predictions]
    df_val_clean["severe_toxicity"] = [p.get("severe_toxicity", np.nan) for p in perspective_predictions]
    df_val_clean["insult"] = [p.get("insult", np.nan) for p in perspective_predictions]
    df_val_clean["threat"] = [p.get("threat", np.nan) for p in perspective_predictions]
    df_val_clean["identity_attack"] = [p.get("identity_attack", np.nan) for p in perspective_predictions]
    
    print(f"Successful predictions: {df_val_clean['perspective_ok'].sum()} / {len(df_val_clean)}")
else:
    df_val_clean["perspective_score"] = np.nan
    df_val_clean["perspective_level"] = np.nan
    df_val_clean["perspective_ok"] = False
    df_val_clean["severe_toxicity"] = np.nan
    df_val_clean["insult"] = np.nan
    df_val_clean["threat"] = np.nan
    df_val_clean["identity_attack"] = np.nan


Perspective API:   0%|          | 0/1043 [00:00<?, ?it/s]

Perspective API: 100%|██████████| 1043/1043 [21:25<00:00,  1.23s/it]

Successful predictions: 1042 / 1043


In [27]:
predictions_output_path = output_dir / 'validation_predictions.csv'
df_val_clean.to_csv(predictions_output_path, index=False)
print(f"Saved: {predictions_output_path}")


Saved: ..\data\processed\validation_predictions.csv


In [28]:
# Save validation predictions as Excel
excel_output_path = output_dir / 'validation_predictions.xlsx'
try:
    df_val_clean.to_excel(excel_output_path, index=False, engine='openpyxl')
    print(f"Excel file saved to: {excel_output_path}")
except ImportError:
    try:
        df_val_clean.to_excel(excel_output_path, index=False, engine='xlsxwriter')
        print(f"Excel file saved to: {excel_output_path}")
    except ImportError:
        print("No Excel engine available. Install openpyxl or xlsxwriter")


Excel file saved to: ..\data\processed\validation_predictions.xlsx


In [29]:
if 'perspective_level' in df_val_clean.columns:
    predicted_counts = df_val_clean['perspective_level'].value_counts().sort_index()
    
    counts = {}
    for level in [1, 2, 3, 4]:
        count = predicted_counts.get(float(level), predicted_counts.get(level, 0))
        counts[level] = int(count)
    
    missing_count = df_val_clean['perspective_level'].isna().sum()
    total_predictions = len(df_val_clean)
    valid_predictions = total_predictions - missing_count
    
    print("Predicted Value Counts:")
    print(f"1: {counts[1]:,} ({counts[1]/valid_predictions*100:.2f}%)")
    print(f"2: {counts[2]:,} ({counts[2]/valid_predictions*100:.2f}%)")
    print(f"3: {counts[3]:,} ({counts[3]/valid_predictions*100:.2f}%)")
    print(f"4: {counts[4]:,} ({counts[4]/valid_predictions*100:.2f}%)")
    print(f"Missing: {missing_count:,}")
    print(f"Total: {total_predictions:,}")


Predicted Value Counts:
1: 790 (75.82%)
2: 199 (19.10%)
3: 51 (4.89%)
4: 2 (0.19%)
Missing: 1
Total: 1,043


## Section 5: Performance Evaluation

Calculate accuracy, precision, recall, F1 scores, and confusion matrices for each model.


In [30]:
def evaluate_model(y_true, y_pred, model_name):
    mask = ~(pd.isna(y_true) | pd.isna(y_pred))
    y_true_clean = y_true[mask]
    y_pred_clean = y_pred[mask]
    
    if len(y_true_clean) == 0:
        return None
    
    accuracy = accuracy_score(y_true_clean, y_pred_clean)
    precision, recall, f1, support = precision_recall_fscore_support(
        y_true_clean, y_pred_clean, average=None, labels=[1, 2, 3, 4], zero_division=0
    )
    macro_precision, macro_recall, macro_f1, _ = precision_recall_fscore_support(
        y_true_clean, y_pred_clean, average='macro', zero_division=0
    )
    cm = confusion_matrix(y_true_clean, y_pred_clean, labels=[1, 2, 3, 4])
    
    return {
        'model_name': model_name,
        'accuracy': accuracy,
        'precision_per_class': dict(zip([1, 2, 3, 4], precision)),
        'recall_per_class': dict(zip([1, 2, 3, 4], recall)),
        'f1_per_class': dict(zip([1, 2, 3, 4], f1)),
        'support_per_class': dict(zip([1, 2, 3, 4], support)),
        'macro_precision': macro_precision,
        'macro_recall': macro_recall,
        'macro_f1': macro_f1,
        'confusion_matrix': cm,
        'n_samples': len(y_true_clean)
    }


In [31]:
results = {}

if df_val_clean['perspective_level'].notna().sum() > 0:
    perspective_results = evaluate_model(
        df_val_clean['toxicity_level'],
        df_val_clean['perspective_level'],
        'Perspective API'
    )
    
    if perspective_results:
        results['perspective'] = perspective_results
        print(f"Accuracy: {perspective_results['accuracy']:.4f}")
        print(f"Macro F1: {perspective_results['macro_f1']:.4f}")
        print("\nPer-class F1 scores:")
        for level in [1, 2, 3, 4]:
            print(f"  Level {level}: {perspective_results['f1_per_class'][level]:.4f} (support: {perspective_results['support_per_class'][level]})")
        print("\nConfusion Matrix:")
        print(perspective_results['confusion_matrix'])


Accuracy: 0.6804
Macro F1: 0.3044

Per-class F1 scores:
  Level 1: 0.8121 (support: 828)
  Level 2: 0.2426 (support: 172)
  Level 3: 0.1628 (support: 35)
  Level 4: 0.0000 (support: 7)

Confusion Matrix:
[[657 142  27   2]
 [113  45  14   0]
 [ 17  11   7   0]
 [  3   1   3   0]]


## Section 6: Error Analysis

Examine cases where models disagree with expert annotations to understand failure modes.


In [32]:
def analyze_errors(df, model_col, expert_col='toxicity_level', n_examples=10):
    df_errors = df.copy()
    df_errors['error'] = abs(df_errors[model_col] - df_errors[expert_col])
    df_errors = df_errors[df_errors[model_col].notna()].copy()
    df_errors = df_errors.sort_values('error', ascending=False)
    
    print(f"Top {n_examples} largest prediction errors:")
    for idx, row in df_errors.head(n_examples).iterrows():
        print(f"\nGround Truth: {row[expert_col]}, Predicted: {row[model_col]}, Error: {row['error']}")
        print(f"Text: {row['comment_text'][:200]}...")
    
    return df_errors

if 'perspective' in results:
    perspective_errors = analyze_errors(df_val_clean, 'perspective_level', n_examples=5)


Top 5 largest prediction errors:

Ground Truth: 4, Predicted: 1.0, Error: 3.0
Text: Harper is a terrible economic manager because he ran nine consecutive deficits! That is proof of his hidden agenda! Balancing the budget was part of his hidden agenda. More proof he has a hidden agend...

Ground Truth: 4, Predicted: 1.0, Error: 3.0
Text: The left-wing city council will always vote to protect the entrenched cartel system. They are generally against the Conservative ideas of free market/technology etc which is what Uber is basically doi...

Ground Truth: 1, Predicted: 4.0, Error: 3.0
Text: If the 'populace' of Toronto can vote in an idiot like Rob Ford, we shouldn't be surprised that the Donald won easily in the USA. Another vote of the malcontent....

Ground Truth: 1, Predicted: 4.0, Error: 3.0
Text: What a stupid article. I this what passes as scholarship?...

Ground Truth: 4, Predicted: 1.0, Error: 3.0
Text: How many plates do you own, Randy? Business hurting?...


## Section 7: Save Evaluation Results

Save evaluation metrics and mapping information for use in subsequent notebooks.


In [33]:
import json

evaluation_summary = {
    'evaluation_date': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S'),
    'validation_samples': len(df_val_clean),
}

for model_key, model_results in results.items():
    evaluation_summary[f'{model_key}_accuracy'] = model_results['accuracy']
    evaluation_summary[f'{model_key}_macro_f1'] = model_results['macro_f1']

evaluation_output_path = output_dir / 'evaluation_results.json'
with open(evaluation_output_path, 'w') as f:
    json.dump(evaluation_summary, f, indent=2)

for model_key in results.keys():
    print(f"{results[model_key]['model_name']}: Accuracy={results[model_key]['accuracy']:.4f}, Macro F1={results[model_key]['macro_f1']:.4f}")

mapping_info = {
    'method': 'equal_bins',
    'description': 'Equal width bins: 0-0.25→1, 0.25-0.5→2, 0.5-0.75→3, 0.75-1.0→4'
}

mapping_output_path = output_dir / 'toxicity_mapping_info.json'
with open(mapping_output_path, 'w') as f:
    json.dump(mapping_info, f, indent=2)


Perspective API: Accuracy=0.6804, Macro F1=0.3044


## Summary

### Key Outputs

1. **Validation Predictions**: `validation_predictions.csv` - All model predictions on validation set
2. **Evaluation Results**: `evaluation_results.json` - Performance metrics
3. **Toxicity Mapping Info**: `toxicity_mapping_info.json` - Mapping method used for 1-4 scale

### Next Steps

- Use Perspective API to annotate sampled comments
- The mapping function (`map_to_4_level_scale`) should be reused with the same method
